export * from './amount.service';
import { AmountService } from './amount.service';
export * from './category.service';
import { CategoryService } from './category.service';
export * from './cuisinetype.service';
import { CuisinetypeService } from './cuisinetype.service';
export * from './difficultylevel.service';
import { DifficultylevelService } from './difficultylevel.service';
export * from './image.service';
import { ImageService } from './image.service';
export * from './ingredient.service';
import { IngredientService } from './ingredient.service';
export * from './instruction.service';
import { InstructionService } from './instruction.service';
export * from './metadata.service';
import { MetadataService } from './metadata.service';
export * from './preparationtime.service';
import { PreparationtimeService } from './preparationtime.service';
export * from './recipe.service';
import { RecipeService } from './recipe.service';
export * from './search.service';
import { SearchService } from './search.service';
export * from './tag.service';
import { TagService } from './tag.service';
export * from './unit.service';
import { UnitService } from './unit.service';
export const APIS = [AmountService, CategoryService, CuisinetypeService, DifficultylevelService, ImageService, IngredientService, InstructionService, MetadataService, PreparationtimeService, RecipeService, SearchService, TagService, UnitService];
