/**
 * Cookbook
 *
 * Contact: github@hulsbus.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about a category
 */
export interface Category { 
    /**
     * ID of a category
     */
    id: string;
    /**
     * Name of a category
     */
    name: string;
}

