/**
 * Cookbook
 *
 * Contact: github@hulsbus.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about a Cuisine Type
 */
export interface CuisineType { 
    /**
     * ID of a cuisine type
     */
    id: string;
    /**
     * name of a cuisine type
     */
    name: string;
}

