/**
 * Cookbook
 *
 * Contact: github@hulsbus.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about a Dificulty Level
 */
export interface DifficultyLevel { 
    /**
     * ID of a Dificulty Level
     */
    id: string;
    /**
     * name of a Dificulty Level
     */
    level: number;
}

