/**
 * Cookbook
 *
 * Contact: github@hulsbus.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model returns information about the queried mediaID
 */
export interface ImageData { 
    /**
     * ID of the requested media resource
     */
    id: string;
    /**
     * type of entity associated to the media file
     */
    entity_type: string;
    /**
     * ID of the entity associated to the media file
     */
    entity_id: string;
    /**
     * size of the media file
     */
    size: number;
    /**
     * type of media
     */
    type: string;
}

