/**
 * Cookbook
 *
 * Contact: github@hulsbus.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Returns information about an ingredient
 */
export interface Ingredient { 
    /**
     * ID of the ingredient
     */
    id: string;
    /**
     * Name of the ingredient
     */
    name: string;
}

