/**
 * Cookbook
 *
 * Contact: github@hulsbus.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about an instruction. 
 */
export interface Instruction { 
    /**
     * ID of the instruction
     */
    id: string;
    /**
     * Sequence position of the instruction
     */
    sequence: number;
    /**
     * instruction content 
     */
    description: string;
    /**
     * mediaID associated to the instruction
     */
    media_id: string;
    /**
     * entity ID the instruction belongs to
     */
    entity_id: string;
    entity_type: string;
}

