/**
 * Cookbook
 *
 * Contact: github@hulsbus.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Definition of an error returned
 */
export interface ModelError { 
    /**
     * field specifying the error that the API encountered
     */
    error: string;
}

