/**
 * Cookbook
 *
 * Contact: github@hulsbus.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about a Peparation Time
 */
export interface PreparationTime { 
    /**
     * ID of a Peparation Time 
     */
    id: string;
    /**
     * name of a Peparation Time
     */
    duration: number;
}

