/**
 * Cookbook
 *
 * Contact: github@hulsbus.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CuisineType } from './cuisineType';
import { Category } from './category';
import { DifficultyLevel } from './difficultyLevel';
import { Tag } from './tag';


/**
 * Model of metadata associated to a recipe
 */
export interface RecipeMetadata { 
    recipe_id: string;
    categories: Array<Category>;
    cuisine_type: CuisineType;
    tags: Array<Tag>;
    difficulty_level: DifficultyLevel;
    preparation_time: number;
    serving_count: number;
}

