/**
 * Cookbook
 *
 * Contact: github@hulsbus.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about a tag
 */
export interface Tag { 
    /**
     * ID of the tag
     */
    id: string;
    /**
     * Name of the tag
     */
    name: string;
}

