/**
 * Cookbook
 *
 * Contact: github@hulsbus.be
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Returns information about a unit of measurement
 */
export interface Unit { 
    /**
     * ID of the unit
     */
    id: string;
    /**
     * Full name of the unit
     */
    full_name: string;
    /**
     * Abbreviation of the unit
     */
    short_name: string;
}

